### ISSUE TITLE
Add to the wiki options for winget

### ISSUE THREAD

**Issue by crramirez** [RamonUnch/AltDrag#78]
Hello,

I cannot make a PR to the wiki so I leave the modifications here:

-----------------------------------
Also, you can use winget:
```powershell
winget install altdrag
winget upgrade altdrag
winget uninstall altdrag
```
If you want to install/upgrade or uninstall altdrag.

-----------------------------------------------------
I submitted the manifest today and it is now available.

https://github.com/microsoft/winget-pkgs/blob/master/manifests/a/AltDrag/AltDrag/1.4/AltDrag.AltDrag.yaml

Regards,
Carlos

**Comment by RamonUnch** [comment]
@crramirez 
The [winget package ](https://github.com/RamonUnch/AltDrag/issues/62)*should* not be this fork but the [original AltDrag ](https://github.com/stefansundin/altdrag/issues/)from Stefan instead.
[I will rename the project](https://github.com/RamonUnch/AltDrag/issues/63) soon after the next bug-fixes release.
I took the choco package indeed but it was before being able to know Stefan's desire for the project. 
See: https://github.com/stefansundin/altdrag/issues/124
and https://github.com/stefansundin/altdrag/discussions/128

**Comment by crramirez** [comment]
The original is still there. https://github.com/microsoft/winget-pkgs/blob/master/manifests/a/AltDrag/AltDrag/1.1/AltDrag.AltDrag.yaml

I checked before that the latest release was in 2015. Also, that you made pull requests to the original project with all your enhancements and they were never merged. For me, it is a dead project. 

I read the links. So, I can:

1. Delete this version entirely,
2. Change the description to clarify this is not the official one.

See this: 
![image](https://user-images.githubusercontent.com/8397379/124027211-e6a7c600-d9f2-11eb-8afc-5dac89a08abb.png)

As you can see forks live also in winget.

What do you want me to do?

**Comment by RamonUnch** [comment]
> 2. Change the description to clarify this is not the official one.

Yes please, 
and actually thanks for helping with the project, it is very appreciated.
It just needs to be clear that it is not maintained by its original author.

**Comment by crramirez** [comment]
You are very welcome, thanks for keeping it alive:

Like this?
```yaml
PackageIdentifier: AltDrag.AltDrag
Publisher: AltDrag
PackageName: AltDrag
Author: Raymond Gillibert
PackageVersion: 1.4
License: GNU General Public License v3.0
InstallerType: nullsoft
LicenseUrl: https://github.com/RamonUnch/AltDrag/blob/main/License.txt
Moniker: altdrag
Tags:
- altdrag
ShortDescription: Easily drag windows when pressing the alt key
PackageUrl: https://github.com/RamonUnch/AltDrag/wiki
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/RamonUnch/AltDrag/releases/download/1.44/AltDrag1.44-inst.exe
  InstallerSha256: 0C587691DFD2BB5A65D54EF6B7BE36997EDAB98B55E3AB1D4A0508DA8602A48F
PackageLocale: en-US
ManifestType: singleton
ManifestVersion: 1.0.0
```
